//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skillz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseDO
    {
        public int Id { get; set; }
        public string ExerciseDescription { get; set; }
        public int SportDOId { get; set; }
    
        public virtual SportDO Sport { get; set; }
    }
}
