//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skillz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SportDO()
        {
            this.Exsercise = new HashSet<ExerciseDO>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual SkillDO Skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExerciseDO> Exsercise { get; set; }
    }
}
